### ISSUE TITLE
Teacher user story

### ISSUE THREAD

**Issue by JOCPhys** [JOCPhys/PREVENT-Project-JOC#1]
As a teacher, I want to understand how the PREVENT strategy impacts my classroom, so I can recognize and respond to potential radicalization.

**Acceptance** Criteria:**

- [x] Access to detailed explanations of PREVENT.
- [x] Guidance on how to spot signs of radicalization.
- [x] Resources for classroom activities to promote understanding.

**TASKS**

- [x] table of links
