### ISSUE TITLE
Parents user story

### ISSUE THREAD

**Issue by JOCPhys** [JOCPhys/PREVENT-Project-JOC#3]
As a parent, I want to be informed about the PREVENT strategy, so I can support my child and recognize any concerning behaviours.

**Acceptance Criteria:**

- [x] Information on what PREVENT is and how it works.
- [x] Tips on discussing sensitive topics with children.
- [x] Contacts for seeking advice and reporting concerns.

**Tasks**

- [x] Include information video 
- [x] Include a table of links to relevant resources
