### ISSUE TITLE
Media links to videos

### ISSUE THREAD

**Issue by JOCPhys** [JOCPhys/PREVENT-Project-JOC#6]
As an individual seeking information on the UK Prevent website, I want to watch YouTube videos related to the Prevent strategy, so I can better understand the initiative through engaging visual content.

**Acceptance Criteria**:

- [x] Easily accessible YouTube video sections on the website.
- [x] Ability to play, pause, and control the videos directly on the site.

**Tasks**

- [x] include a what is prevent video in header
- [x] include social media link to relevant youtube search in footer
